name: WakaTime Metrics

on:
  schedule:
    - cron: '30 18 * * *'  # Runs daily at 12 AM IST
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

