name: WakaTime Metrics

on:
  schedule:
    - cron: '0 3 * * *'  # Runs daily at 6 AM EAT (3 AM UTC)
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

